apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: zipkin
  namespace: istio-system
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
